### ISSUE TITLE
Any plans to update this gem? 

### ISSUE THREAD

**Issue by rsedighi** [aha-app/aha-api#1]
Bundle install fails because the dependencies are out of date: 

`Bundler could not find compatible versions for gem "faraday":
  In snapshot (Gemfile.lock):
    faraday (= 0.10.1)

  In Gemfile:
    aha-api was resolved to 1.0.13, which depends on
      faraday (~> 0.9.0)

    aha-api was resolved to 1.0.13, which depends on
      faraday_middleware was resolved to 0.11.0.1, which depends on
        faraday (< 1.0, >= 0.7.4)

    omniauth-google-oauth2 was resolved to 0.4.1, which depends on
      omniauth-oauth2 (>= 1.3.1) was resolved to 1.4.0, which depends on
        oauth2 (~> 1.0) was resolved to 1.3.0, which depends on
          faraday (< 0.11, >= 0.8)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

**Comment by schneidmaster** [comment]
Hi there -- it looks like you have faraday locked to `0.10.1` in your Gemfile; is there a reason you can't just use 0.9? That would satisfy all of the dependency requirements.

We may update the gem at some point but will need to test for any breaking changes.

**Comment by rsedighi** [comment]
You're right @schneidmaster - updating faraday in the gem's gemspec resolved the issue.
