### ISSUE TITLE
Security Issue: Vulnerable Component activesupport@6.1.4.1

### ISSUE THREAD

**Issue by sectheops** [aha-app/aha-api#17]
Seeing that you all are using activesupport@6.1.4.1

It has about 3 CVEs associated with it.

https://security.snyk.io/vuln/SNYK-RUBY-ACTIVESUPPORT-3360028
https://security.snyk.io/vuln/SNYK-RUBY-ACTIVESUPPORT-3237242
https://security.snyk.io/vuln/SNYK-RUBY-ACTIVESUPPORT-5851458

Recommendation:
Upgrade activesupport to version 6.1.7.5, 7.0.7.1 or higher.

**Comment by cornu-ammonis** [comment]
Thank you for your report. I have removed the lockfile in https://github.com/aha-app/aha-api/pull/18. The lockfile was not necessary as this is only used as a dependency; consumers of the gem will lock to their specific versions in their own lockfiles and compatibility ranges are set in the gemspec.
